steps.web/routes/web.php
<?php
/**
 * @fopyright Copyright (c) 2017 - 2018.
 * @author Kevin Alexander Gaitan Arguello
 * @email kevinnica02@hotmail.com
 * @date 6/28/18 9:00 PM
 * @portfolio https://gitlab.com/alcard24
 *
 */

//------------------------<Landing routes>-----------------------------------------------------------------------
Route::get('/', function () {
    return view('/landing/index');
});
Route::get('index', function () {
    return view('/landing/index');
});

//------------------------<Landing routes>-----------------------------------------------------------------------


//------------------------<Authentication routes>-----------------------------------------------------------------------
Auth::routes();
//------------------------<Authentication routes>-----------------------------------------------------------------------

Route::get('/dashboard', 'HomeController@index')->name('home');

Route::group(['middleware' => ['role:developer']], function () {

    //------------------------<Rol routes>-----------------------------------------------------------------------------
    Route::resource('/dashboard/role', 'RoleController');
    Route::get('/dashboard/role/retrieveAll', 'RoleController@retrieveAllRoles')->name('role.retrieveAll');
    //------------------------<Rol routes>-----------------------------------------------------------------------------

    //------------------------<Permission routes>-----------------------------------------------------------------------
    Route::resource('/dashboard/permission', 'PermissionController');
    Route::get('/ajax/index/permission', 'PermissionController@indexAjax')->name('permission.indexAjax');
    //------------------------<Permission routes>-----------------------------------------------------------------------

    //------------------------<Enclosure routes>------------------------------------------------------------------------
    Route::resource('/dashboard/enclosure', 'EnclosureController');
    Route::get('/ajax/delete/enclosure', 'EnclosureController@ajaxDelete')->name('enclosure.remove');
    Route::get('/ajax/index/enclosure', 'EnclosureController@ajaxIndex')->name('enclosure.indexAjax');
    //------------------------<Enclosure routes>------------------------------------------------------------------------

    //------------------------<User routes>----------------------------------------------------------------------------
    Route::resource('/dashboard/user', 'UserController');
    Route::post('/ajax/delete/user', 'UserController@ajaxDelete')->name('user.remove');
    Route::get('/ajax/index/user', 'UserController@ajaxIndex')->name('user.indexAjax');
    Route::post('/ajax/delete/user', 'UserController@ajaxDelete')->name('user.remove');
    Route::get('/ajax/index/user', 'UserController@ajaxIndex')->name('user.indexAjax');
    //------------------------<User routes>----------------------------------------------------------------------------

    //------------------------<Institution routes>----------------------------------------------------------------------
    Route::resource('/dashboard/institution', 'InstitutionController');
    Route::get('/ajax/find/institution', 'InstitutionController@findAjax')->name('institution.find');
    Route::get('/ajax/delete/institution', 'InstitutionController@ajaxDelete')->name('institution.remove');
    Route::get('/ajax/index/institution', 'InstitutionController@ajaxIndex')->name('institution.indexAjax');
    Route::get('/ajax/show/institution', 'InstitutionController@indexAjaxSelect')->name('institution.indexAjaxSelect');
    //------------------------<Institution routes>----------------------------------------------------------------------

    //------------------------<Catalogue routes>----------------------------------------------------------------------
    Route::resource('/dashboard/catalogue', 'CatalogueController');
    Route::get('/ajax/delete/catalogue', 'CatalogueController@ajaxDelete')->name('catalogue.remove');
    Route::get('/ajax/index/catalogue/{valor?}', 'CatalogueController@ajaxIndex')->name('catalogue.indexAjax');
    Route::get('/ajax/show/catalogue', 'CatalogueController@indexAjaxSelect')->name('catalogue.indexAjaxSelect');
    Route::get('/ajax/select/catalogue', 'CatalogueController@findCatalogo')->name('catalogue.find');
    //------------------------<Catalogue routes>----------------------------------------------------------------------

    //------------------------<Career routes>----------------------------------------------------------------------
    Route::resource('/dashboard/career', 'CareerController');
    Route::get('/ajax/index/career/{value?}', 'CareerController@ajaxIndex')->name('career.indexAjax');
    //------------------------<Career routes>----------------------------------------------------------------------

    //------------------------<IconResource routes>----------------------------------------------------------------------
    Route::resource('/iconresource', 'IconResourceController');
    //------------------------<IconResource routes>----------------------------------------------------------------------

});

//------------------------<Landing routes>-----------------------------------------------------------------------------
Route::get('/privacy', function () {
    return view('landing.footerPages.privacy');
});
Route::get('/about', function () {
    return view('landing.footerPages.about');
});
Route::get('/terms', function () {
    return view('landing.footerPages.terms');
});
Route::get('/careers', function () {
    return view('layouts.search');
});
//------------------------<Landing routes>-----------------------------------------------------------------------------

//------------------------<Icon Resources routes>-----------------------------------------------------------------------
Route::resource('/IconResource', 'IconResourceController');
//------------------------<Icon Resources routes>-----------------------------------------------------------------------


//
//Route::get('/{vue_capture?}', function () {
//    return view('coreui');
//})->where('vue_capture', '[\/\w\.-]*');

steps.web/app/Http/Controllers/Admin/CareerController.php
<?php
/**
 * @copyright Copyright (c) 2017 - 2018.
 * @author Kevin Alexander Gaitan Arguello
 * @email kevinnica02@hotmail.com
 * @date 7/1/18 6:24 PM
 * @portfolio https://gitlab.com/alcard24
 *
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Steps\Career\Career;
use Validator;
/**
 * Class Career Controller
 * @package App\Http\Controllers
 */
class CareerController extends Controller
{
    /**
     * Index, Method GET
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index() {
        return view('dashboard.career.index', ['url' => 'dashboard/career']);
    }

    public function create() {
        return view('dashboard.career.edit');
    }

    public function store(Request $request) {
        //the validation gave me a lot of errors so i finally made this:
        //Request Validation Without redirect
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255|regex:/^([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-])+((\s*)+([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-]*)*)+$/',
            'career_select' => 'nullable|integer',
            'content' => 'nullable|integer'
        ]);
        //If exists error in the validation then
        if ($validator->fails()) {
            //return json with errors list and action for take a decision in the js
            return response()->json([
                'errors' => $validator->errors(),
                'action' => 1
            ],400); //with error state 400
        }

        Career::create([
            'name' => $request['name'],
            'especial_of' => $request['career_select'],
        ]);
        return response()->json(['action' => 0]);
    }

    public function edit($id)
    {
        $career = Career::findOrFail($id);
        return view('dashboard.career.edit', ['career' => $career]);
    }

    public function update(Request $request, $usuario)
    {
        //Kavv
        //Email is unique but when u make update, u must validate.. because exist or not this email
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255|regex:/^([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-])+((\s*)+([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-]*)*)+$/',
            'career_select' => 'nullable|integer',
            'content' => 'nullable|integer'
        ]);

        //If exists error in the validation then
        if ($validator->fails()) {
            //return json with errors list and action for take a decision in the js
            return response()->json([
                'errors' => $validator->errors(),
                'action' => 1
            ],400);
        }

        $career = Career::find($usuario);
        $career->name = $request->get('name');
        if($request->get('career_select'))
            $career->especial_of = $request->get('career_select');
        $career->update();

        return response()->json(['action' => 0]);

    }
    public function destroy($id)
    {
        $career = Career::find($id);
        $career->delete();
        return 0;
    }
    public function ajaxIndex($id = null, Request $x)
    {
        if($id == null)
            $data = Career::all();
        else
            $data = Career::where('id', '!=', $id)->get();
        return Datatables::of($data)
            ->addColumn('id', function (Career $data) {
                return '<span data-id="' . $data->id . '" data-nombre="' . $data->name . '"></span>';
            })
            ->addColumn('specialPosition', function (Career $data) {
                if ($data->especial_of == null) {
                    return '<span class="label label-danger">NINGUNO</span>';
                } else
                    return '<span class="label label-primary">' . $data->getMaster->name . '</span>';
            })
            ->addColumn('content', function (Career $data) {
                if ($data->table_content == null) {
                    return '<span class="label label-danger">NINGUNO</span>';
                } else
                    return '<span class="label label-primary">' . $data->table_content . '</span>';
            })
            ->addColumn('created_at', function (Career $data) {
                return $data->created_at->diffForHumans();
            })
            ->addColumn('action', function (Career $data) {
                return
                    '<a href="' . route('career.edit', $data->id) . '"' . '<button type="button" rel="tooltip" class="btn btn-success btn-simple"  data-original-title="" title="">' .
                    '<i class="material-icons" > edit</i></button ></a >' .
                    '<button rel="tooltip" class="btn btn-danger btn-simple remove" data-original-title="" title="" data-info="' . $data->id . '"> <i class="material-icons">close</i> </button>';
            })
            ->rawColumns(['id', 'specialPosition', 'content', 'action'])
            ->make(true);
    }
}

steps.web/resources/views/dashboard/career/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    @if(isset($career))
        {{ Breadcrumbs::render('career.edit',$career) }}
    @else
        {{ Breadcrumbs::render('career.create') }}
    @endif

    <div class="header text-center">
        <h3 class="title">
            @if(isset($career))
                Modificando {{$career->name}} [{{$career->id}}]
            @else
                Agregar una nueva carrera
            @endif
        </h3>
    </div>

    <div class="col-md-12">
        <!-- Kavv -->
        <!-- Added a tag with id "mensaje" for use with the tiposmensajes script -->
        <div id="mensaje"></div>

        <div class="card">
            <div class="card-header">

            </div>
            <div class="card-content">
                @if(isset($career))
                {!! Form::model($career, ['url' => ['dashboard/user', $career->id], 'method' => 'patch', 'id' => 'data'])  !!}
                @else
                <!-- Kavv -->
                <!-- changed the tag because it wasn't necessary -->
                <form id="data">
                @endif
                    <!-- Kavv -->
                    <!-- Added tag for token -->
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" id="token">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group label-floating @if(!isset($career)) is-empty @endif">
                                <label for="name" class="control-label">Name</label>
                                <input name="name" type="text"
                                    @if(isset($career))
                                    value="{{$career->name}}"
                                    @endif
                                    class="form-control material-input">
                            </div>
                        </div>

                        <div class="col-md-6">
                            @include('dashboard.career.select')
                        </div>
                        
                        <div class="col-md-12">
                            <div class="form-group label-floating  @if(!isset($career)) is-empty @endif">
                                <label for="content" class="control-label">Content</label>
                                <input name="content" type="text" 
                                    @if(isset($career))
                                    value="{{$career->table_content}}"
                                    @endif
                                    class="form-control material-input">
                            </div>

                        </div>
                    </div>        
                    <!-- Kavv -->
                    <!-- Condition to select the button acctions -->
                    @if(isset($career))
                    <button class="btn btn-success" type="button" onclick="Update();">
                    @else
                    <button class="btn btn-success" type="button" onclick="Save()">
                    @endif
                        Guardar
                        <div class="ripple-container"></div>
                    </button>
                {{ Form::close()}}
            </div>
        </div>
    </div>
@stop
@section('javascript')
    <!-- Include Editor style. -->
    <link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.6/css/froala_editor.min.css'
          rel='stylesheet' type='text/css'/>

    <!-- Include JS file. -->
    <script type='text/javascript'
            src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.6/js/froala_editor.min.js'></script>
    
    <!-- Mensaje -->
    <script src="/js/kavv/tiposmensajes.js"></script>
    
    <!-- Initialize the editor. -->
    <script>
        $(document).ready(function () {

        });

        @if(isset($career))
        //Update user
        function Update()
        {
            return $.ajax({
                url: '{{route('career.update',$career->id)}}',
                headers: {'X-CSRF-TOKEN': $("#token").val()},
                type: 'PUT',
                dataType: 'json',
                data: $("#data").serialize(),
                success: function(res){
                    if(res.action === 1)
                        //message([Message Array], {manual:bool,objeto:$(#),tipo:'danger,info,success, etc'})
                        message(res.message, {manual:true, tipo:'danger'});                  
                    else
                        location.href = "/dashboard/career";
                }
            }).fail( function( jqXHR, textStatus, errorThrown ) {
                message(jqXHR,{tipo:"danger"});
            });
        }
        @else 
        //Save User
        function Save()
        {
            return $.ajax({
                url: '{{route('career.store')}}',
                headers: {'X-CSRF-TOKEN': $("#token").val()},
                type: 'POST',
                dataType: 'json',
                data: $("#data").serialize(),
                success: function(res){
                    if(res.action === 1)
                        message(res.message, {manual:true, tipo:'danger'});                    
                    else
                        location.href = "/dashboard/career";
                }
            }).fail( function( jqXHR, textStatus, errorThrown ) {
                message(jqXHR,{tipo:"danger"});
            });
        }
        @endif
    </script>

    @parent
@stop

steps.web/resources/views/dashboard/career/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {{ Breadcrumbs::render('career.index') }}

    <div class="header text-center">
        <h3 class="title">Carreras registradas en el sistema.</h3>
        <p class="category">lista de carreras</p>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-content">
                    {{--@include('dashboard.partials.search')--}}
                    <div class="toolbar" style="display: inline-block; width: 100%;">
                        <div class="pull-left">
                            <div class="btn-group pull-left" style="margin-right: 10px">
                                <a href="{{action('CareerController@create')}}">
                                    <button class="btn btn-sm btn-success">
                                        <i class="material-icons">save</i>&nbsp;&nbsp;Nuevo
                                    </button>
                                </a>
                            </div>
                        </div>
                        <div class="pull-right">
                            <div class="btn-group pull-right" style="margin-right: 10px">
                                <button class="btn btn-sm reload btn-facebook btn-raised">
                                    <i class="material-icons">replay</i>&nbsp;&nbsp;Recargar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="material-datatables">
                        <table id="datatables" class="table table-striped table-no-bordered table-hover"
                               cellspacing="0"
                               width="100%" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Special Of</th>
                                    <th>Content</th>
                                    <th>Created at</th>
                                    <th class="text-left">Options</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true" style="display: none;">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn btn-simple close" data-dismiss="modal"
                                        aria-hidden="true">
                                    <i class="material-icons">clear</i>
                                </button>
                                <h4 class="modal-title"></h4>
                            </div>
                            <div class="modal-body">
                                <p class="description-modal">Esta seguro ?</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-simple" data-dismiss="modal">Cancelar</button>
                                <button type="button" class="btn btn-danger btn-simple delete" data-dismiss="modal">
                                    Sí
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('javascript')

    <script type="text/javascript">
    
        var table, theValue, row;

        $(document).ready(function () {
            table = $('#datatables').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{route('career.indexAjax')}}',
                columns: [
                    {data: 'name', name: 'name'},
                    {data: 'specialPosition', name: 'specialPosition'},
                    {data: 'content', name: 'content'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
                columnDefs: [
                    {className: "td-actions text-right", "targets": [4]}
                ],
                "lengthMenu": [
                    [10, 25, 50],
                    [10, 25, 50]
                ],
                responsive: true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search records",
                    lengthMenu: "Ver _MENU_ por página",
                    zeroRecords: "No se encontraron coincidencias - :c",
                    info: "Página _PAGE_ de _PAGES_",
                    infoEmpty: "No hay datos",
                    paginate: {
                        first: "Primero",
                        last: "Último",
                        next: "Siguiente",
                        previous: "Anterior"
                    },
                    sProcessing: "<div id=\"contenedor\"><div class=\"loader\" id=\"loader\">Loading...</div></div>"
                }

            });
        });
        
        $(document).on('click', '.remove', function () {
            $('.description-modal').text("Esta seguro que desea eliminar este registro");
            $('#myModal').modal('show');
            theValue = $(this).data('info');
            row = $(this).parents('tr');
            console.log($(this).parents('tr'));
        });
        $(document).on('click', '.delete', function (e) {
            $.ajax(
                {
                    type: "DELETE",
                    url: '/dashboard/career/' + theValue,
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    dataType: 'json',
                    success: function (res) {
                        table.row(row).remove().draw( false );
                    }
                }
            );
        });
        $(document).on('click', '.reload', function (e) {
            location.reload();
        });
    </script>
    @parent
@stop

steps.web/resources/views/dashboard/career/select.blade.php
<style type="text/css">
    .modal {
        text-align: center;
    }

    @media screen and (min-width: 768px) {
        .modal:before {
            display: inline-block;
            vertical-align: middle;
            content: " ";
            height: 100%;
        }
    }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }

    .table > tbody > tr.selected > td, .table > tbody > tr.selected > th, .table > tbody > tr > td.selected, .table > tbody > tr > th.selected, .table > tfoot > tr.selected > td, .table > tfoot > tr.selected > th, .table > tfoot > tr > td.selected, .table > tfoot > tr > th.selected, .table > thead > tr.selected > td, .table > thead > tr.selected > th, .table > thead > tr > td.selected, .table > thead > tr > th.selected {
        background-color: #FF9800;
        color: white;
    }
</style>

<div class="form-group label-floating @if(!isset($career)) is-empty @endif" id="career-label" onclick="$('#selected_ins').modal().show(); ">
    <label for="career_padre_name" class="control-label">Selecciona una carrera</label>
    <div class="input-group">
        <input type="hidden" name="career_select" id="career_padre_select" style="display: none;" 
            placeholder="" @if(isset($career)) value="{{$career->especial_of}}" @endif >
        <input type="text" id="career_padre_name" class="form-control" readonly autocomplete="false" 
            placeholder="" @if(isset($career)) value="{{$career->getMaster->name}}" @endif >
        <span class="input-group-btn">
            <button class="btn btn-default btn-round" type="button">
                <i class="material-icons">touch_app</i>
            </button>
        </span>
    </div>
</div>
<div class="modal fade" id="selected_ins">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn btn-simple close" data-dismiss="modal"
                        aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Selecciona un carrera</h4>
            </div>
            <div class="modal-body">
                <div class="material-datatables">
                    <table id="data_padre_select"
                           class="table table-no-bordered table-hover"
                           width="100%"
                           cellspacing="0">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Nombre</th>
                            <th>Fecha de creacion</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer ">
                <button class="btn btn-danger" onclick="$('#selected_ins').modal('hide')">Cancelar</button>
                <button class="btn btn-success" id="ins_modal_go">Seleccionar</button>
            </div>
        </div>
    </div>
</div>
@section('javascript')
    <script type="text/javascript">
        $(document).ready(function () {
            @if(isset($career))
                route = '{{route('career.indexAjax',$career->id)}}';
            @else
                route = '{{route('career.indexAjax')}}';
            @endif
            let selectTable = $('#data_padre_select').DataTable({
                processing: true,

                serverSide: true,
                ajax: route,
                columns: [
                    {data: 'id', name: 'id', orderable: false, searchable: false},
                    {data: 'name', name: 'name'},
                    {data: 'created_at', name: 'created_at'}
                ],
                columnDefs: [
                    {className: "td-actions text-right", "targets": [2]}
                ],
                "lengthMenu": [
                    [5, 10],
                    [5, 10]
                ],
                responsive: true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search records",
                    lengthMenu: "Ver _MENU_ por página",
                    zeroRecords: "No se encontraron coincidencias - :c",
                    info: "Página _PAGE_ de _PAGES_",
                    infoEmpty: "No hay datos",
                    paginate: {
                        first: "Primero",
                        last: "Último",
                        next: "Siguiente",
                        previous: "Anterior"
                    },
                    sProcessing: "<div id=\"contenedor\"><div class=\"loader\" id=\"loader\">Loading...</div></div>"
                }

            });
            var data = null;
            var nombre = null;
            $('#data_padre_select tbody').on('click', 'tr', function () {
                if ($(this).hasClass('selected')) {
                    $(this).removeClass('selected');
                    data = null;
                    nombre = null;
                }
                else {
                    selectTable.$('tr.selected').removeClass('selected');
                    $(this).addClass('selected');
                    data = $(this).find('span').data().id;
                    nombre = $(this).find('span').data().nombre;
                }
            });
            $('#ins_modal_go').on('click', function () {
                if (data == null) {
                    showNotification('Debe seleccionar una carrera primero', 'danger');
                }
                else {
                    $('#selected_ins').modal('hide');
                    var theDOM = $('#career_padre_name');
                    var label = $('#career-label');
                    label.removeClass('is-empty');
                    label.addClass('is-focused');
                    $('#career_padre_select').val(data);
                    theDOM.val(nombre);
                }
            });
            $( "#selected_ins" ).on('shown.bs.modal', function(){
                selectTable.ajax.reload();
            });
        });
    </script>
    @parent
@stop