steps.web/routes/web.php
<?php
/**
 * @fopyright Copyright (c) 2017 - 2018.
 * @author Kevin Alexander Gaitan Arguello
 * @email kevinnica02@hotmail.com
 * @date 6/28/18 9:00 PM
 * @portfolio https://gitlab.com/alcard24
 *
 */

//------------------------<Landing routes>-----------------------------------------------------------------------
Route::get('/', function () {
    return view('/landing/index');
});
Route::get('index', function () {
    return view('/landing/index');
});

//------------------------<Landing routes>-----------------------------------------------------------------------


//------------------------<Authentication routes>-----------------------------------------------------------------------
Auth::routes();
//------------------------<Authentication routes>-----------------------------------------------------------------------

Route::get('/dashboard', 'HomeController@index')->name('home');

Route::group(['middleware' => ['role:developer']], function () {

    //------------------------<Rol routes>-----------------------------------------------------------------------------
    Route::resource('/dashboard/role', 'RoleController');
    Route::get('/dashboard/role/retrieveAll', 'RoleController@retrieveAllRoles')->name('role.retrieveAll');
    //------------------------<Rol routes>-----------------------------------------------------------------------------

    //------------------------<Permission routes>-----------------------------------------------------------------------
    Route::resource('/dashboard/permission', 'PermissionController');
    Route::get('/ajax/index/permission', 'PermissionController@indexAjax')->name('permission.indexAjax');
    //------------------------<Permission routes>-----------------------------------------------------------------------

    //------------------------<Enclosure routes>------------------------------------------------------------------------
    Route::resource('/dashboard/enclosure', 'EnclosureController');
    Route::get('/ajax/delete/enclosure', 'EnclosureController@ajaxDelete')->name('enclosure.remove');
    Route::get('/ajax/index/enclosure', 'EnclosureController@ajaxIndex')->name('enclosure.indexAjax');
    //------------------------<Enclosure routes>------------------------------------------------------------------------

    //------------------------<User routes>----------------------------------------------------------------------------
    Route::resource('/dashboard/user', 'UserController');
    Route::post('/ajax/delete/user', 'UserController@ajaxDelete')->name('user.remove');
    Route::get('/ajax/index/user', 'UserController@ajaxIndex')->name('user.indexAjax');
    Route::post('/ajax/delete/user', 'UserController@ajaxDelete')->name('user.remove');
    Route::get('/ajax/index/user', 'UserController@ajaxIndex')->name('user.indexAjax');
    //------------------------<User routes>----------------------------------------------------------------------------

    //------------------------<Institution routes>----------------------------------------------------------------------
    Route::resource('/dashboard/institution', 'InstitutionController');
    Route::get('/ajax/find/institution', 'InstitutionController@findAjax')->name('institution.find');
    Route::get('/ajax/delete/institution', 'InstitutionController@ajaxDelete')->name('institution.remove');
    Route::get('/ajax/index/institution', 'InstitutionController@ajaxIndex')->name('institution.indexAjax');
    Route::get('/ajax/show/institution', 'InstitutionController@indexAjaxSelect')->name('institution.indexAjaxSelect');
    //------------------------<Institution routes>----------------------------------------------------------------------

    //------------------------<Catalogue routes>----------------------------------------------------------------------
    Route::resource('/dashboard/catalogue', 'CatalogueController');
    Route::get('/ajax/delete/catalogue', 'CatalogueController@ajaxDelete')->name('catalogue.remove');
    Route::get('/ajax/index/catalogue/{valor?}', 'CatalogueController@ajaxIndex')->name('catalogue.indexAjax');
    Route::get('/ajax/show/catalogue', 'CatalogueController@indexAjaxSelect')->name('catalogue.indexAjaxSelect');
    Route::get('/ajax/select/catalogue', 'CatalogueController@findCatalogo')->name('catalogue.find');
    //------------------------<Catalogue routes>----------------------------------------------------------------------

    //------------------------<Career routes>----------------------------------------------------------------------
    Route::resource('/dashboard/career', 'CareerController');
    Route::get('/ajax/index/career/{value?}', 'CareerController@ajaxIndex')->name('career.indexAjax');
    //------------------------<Career routes>----------------------------------------------------------------------

    //------------------------<IconResource routes>----------------------------------------------------------------------
    Route::resource('/iconresource', 'IconResourceController');
    //------------------------<IconResource routes>----------------------------------------------------------------------

});

//------------------------<Landing routes>-----------------------------------------------------------------------------
Route::get('/privacy', function () {
    return view('landing.footerPages.privacy');
});
Route::get('/about', function () {
    return view('landing.footerPages.about');
});
Route::get('/terms', function () {
    return view('landing.footerPages.terms');
});
Route::get('/careers', function () {
    return view('layouts.search');
});
//------------------------<Landing routes>-----------------------------------------------------------------------------

//------------------------<Icon Resources routes>-----------------------------------------------------------------------
Route::resource('/IconResource', 'IconResourceController');
//------------------------<Icon Resources routes>-----------------------------------------------------------------------


//
//Route::get('/{vue_capture?}', function () {
//    return view('coreui');
//})->where('vue_capture', '[\/\w\.-]*');

steps.web/app/Http/Controllers/Admin/UserController.php
<?php
/**
 * @copyright Copyright (c) 2017 - 2018.
 * @author Kevin Alexander Gaitan Arguello
 * @email kevinnica02@hotmail.com
 * @date 7/1/18 5:41 PM
 * @portfolio https://gitlab.com/alcard24
 *
 */

namespace App\Http\Controllers;

use App\Steps\User\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Yajra\Datatables\Datatables;
use Validator;
use DB;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

       /**
     * Display a listing of the resource.
     *
     * @param Request $predicate
     * @return \Illuminate\Http\Response
     */
    public function index(Request $predicate)
    {
        return view('dashboard.user.index',['url' => 'dashboard/user']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //set up default configs
 		return view('dashboard.user.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //the validation gave me a lot of errors so i finally made this:
        //Request Validation Without redirect
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:50|regex:/^([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-])+((\s*)+([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-]*)*)+$/',
            'email' => 'required|max:70|email',
            'password' => 'required|between:8,100'
        ]);
        //If exists error in the validation then
        if ($validator->fails()) {
            //return json with errors list and action for take a decision in the js
            return response()->json([
                'errors' => $validator->errors(),
                'action' => 1
            ],400); //with error state 400
        }
        
        //Exists an email same to $request->get('email')
        $query = User::where('email','ilike',$request->get('email'))->get();

        //if $query is greater than 0, imply than the email is in used
        if(count($query) > 0)
        {
            return response()->json([
                'message' => ['El email esta en uso'],
                'action' => 1
            ]);
        }
        //if exist a deleted user with the same email
        $query = User::withTrashed()
                 ->Where('email','ilike',$request->get('email'))
                 ->get();

        //if $query is greater than 0, imply than the user will be restore
        if(count($query) > 0)
        {
            //restore
            $query[0]->deleted_at = null;
            $query[0]->save();
        }
        else
        {
            //create a new user
            $user = new User();
            $user->name = $request->get('name');
            $user->email = $request->get('email');
            $user->password = bcrypt($request->get('password'));
            $user->save();
        }

        return response()->json(['action' => 0]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Enclosure $recinto
     * @return \Illuminate\Http\Response
     */
    public function show(User $usuario)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usuario = User::findOrFail($id);
        return view('dashboard.user.edit', ['usuario' => $usuario]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param $usuario
     * @return \Illuminate\Http\RedirectResponse
     */
    
    public function update(Request $request, $usuario)
    {
        
        //Kavv
        //Email is unique but when u make update, u must validate.. because exist or not this email
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:50|regex:/^([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-])+((\s*)+([0-9a-zA-ZñÑáéíóúÁÉÍÓÚ_-]*)*)+$/',
            'email' => 'required|max:70|email',
            'password' => 'nullable|between:8,100'
        ]);

        //If exists error in the validation then
        if ($validator->fails()) {
            //return json with errors list and action for take a decision in the js
            return response()->json([
                'errors' => $validator->errors(),
                'action' => 1
            ],400);
        }
        $user = User::find($usuario);
        //if the email is the same, not is necessary validate the email
        if($user['email']!=$request->get('email'))
        {
            //query if exists the email
            $consulta = User::where('email','ilike',$request->get('email'))->get();
            if(count($consulta)>0)
            {
                return response()->json([
                    'message' => ['El correo ingresado ya esta en uso'],
                    'action' => 1,
                ]);
            }
            else//if the mail does not exist it can be updated
            {
                $user['email'] = $request->get('email');
            }
        }
        //Changue the password
        if($request->get('changePassword')==1)
        {
            $user['password'] = bcrypt($request->get('password'));
        }

        $user->name = $request->get('name');
        $user->update();

        return response()->json([
            'action' => 0
        ]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($user)
    {
        $user = User::find($user);
        $user->activo = false;
        $user->update();
        return Redirect::to('dashboard/user');

    }

    public function ajaxDelete(Request $request)
    {
        //Kavv
        //Add deleting
        $user = User::find($request['user']);
        $user->delete();
    }

    public function ajaxIndex()
    {
        $data = User::all();
        $htmlDATA = '';
        return Datatables::of($data)
            ->addColumn('action', function ($data) {
                return '<a href="' . route('user.edit', $data->id) . '"' . '<button type="button" rel="tooltip" class="btn btn-success btn-simple"  data-original-title="" title="">' .
                    '<i class="material-icons" > edit</i></button ></a >' .
                    '<button rel="tooltip" class="btn btn-danger btn-simple remove" data-original-title="" title="" data-info="' . $data->id . '"> <i class="material-icons">close</i> </button>';
            })
            ->addColumn('roles',function ($data){
                $htmlDATA = '';
                foreach ($data->roles as $rol) {
                    $htmlDATA .= '<span class="label label-primary">'.$rol->display_name.'</span>';
                }
                return $htmlDATA;
            })
            ->addColumn('created_at', function ($data) {
                return $data->created_at->diffForHumans();
            })
            ->rawColumns(['roles','action'])
            ->make(true);
    }

}

steps.web/resources/views/dashboard/user/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    @if(isset($usuario))
        {{ Breadcrumbs::render('user.edit',$usuario) }}
    @else
        {{ Breadcrumbs::render('user.create') }}
    @endif

    <div class="header text-center">
        <h3 class="title">
            @if(isset($usuario))
                Modificando {{$usuario->name}} [{{$usuario->id}}]
            @else
                Agregar un nuevo usuario
            @endif
        </h3>
    </div>

    <div class="col-md-12">
        <!-- Kavv -->
        <!-- Added a tag with id "mensaje" for use with the tiposmensajes script -->
        <div id="mensaje"></div>
        <!-- Kavv -->
        <!-- this is useless now -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="card">
            <div class="card-header">
            <!-- Kavv -->
            <!-- When u create an user, u don't must show the togglebutton -->
                @if(isset($usuario))
                    <div class="togglebutton">
                        <label>
                            <input type="checkbox" id="canReset" name="can_reset" onchange="hidePassword()">
                            Volver a establecer contraseña
                        </label>
                    </div>
                @endif
            </div>
            <div class="card-content">
                @if(isset($usuario))
                {!! Form::model($usuario, ['url' => ['dashboard/user', $usuario->id], 'method' => 'patch', 'id' => 'data'])  !!}
                @else
                <!-- Kavv -->
                <!-- changed the tag because it wasn't necessary -->
                <form id="data">
                @endif
                    <!-- Kavv -->
                    <!-- Added tags for token and one more for the togle button state  -->
                    <input id="changePassword" type="hidden" name="changePassword" value="0">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" id="token">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group label-floating @if(!isset($usuario)) is-empty @endif">
                                <label for="name" class="control-label">Nombre del usuario</label>
                                <input name="name" type="text"
                                    @if(isset($usuario))
                                    value="{{$usuario->name}}"
                                    @endif
                                    class="form-control material-input">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group label-floating @if(!isset($usuario)) is-empty @endif">
                                <label for="email" class="control-label">Email</label>
                                <input name="email" type="email"
                                    @if(isset($usuario))
                                    value="{{$usuario->email}}"
                                    @endif
                                    class="form-control material-input">
                            </div>
                        </div>
                        <div class="col-md-6" id="divPassword" @if(isset($usuario))hidden
                            style="visibility: hidden; display: none;" @endif>
                            <div class="form-group label-floating  @if(!isset($usuario)) is-empty @endif">
                                <label for="password" class="control-label">Contraseña del usuario</label>
                                <div class="input-group">
                                    <input name="password" type="password"
                                        class="form-control material-input">
                                    <span class="input-group-btn">
                                        <button class="btn btn-round btn-primary" id="limpiar" data-toggle="tooltip" data-placement="top"
                                                title="Limpiar">
                                            <i class="material-icons">clear</i>
                                        </button>

                                        <button class="btn btn-round btn-primary" id="generar_password" data-toggle="tooltip" data-placement="top"
                                                title="Generar contraseña">
                                            <i class="material-icons">settings_backup_restore</i>
                                        </button>
                                    </span>
                                </div>
                            </div>

                        </div>
                    </div>        
                    <!-- Kavv -->
                    <!-- Condition to select the button acctions -->
                    @if(isset($usuario))
                    <button class="btn btn-success" type="button" onclick="Update();">
                    @else
                    <button class="btn btn-success" type="button" onclick="Save()">
                    @endif
                        Guardar
                        <div class="ripple-container"></div>
                    </button>
                {{ Form::close()}}
            </div>
        </div>
    </div>
@stop
@section('javascript')
    <!-- Include Editor style. -->
    <link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.6/css/froala_editor.min.css'
          rel='stylesheet' type='text/css'/>

    <!-- Include JS file. -->
    <script type='text/javascript'
            src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.6/js/froala_editor.min.js'></script>
    
    <!-- Mensaje -->
    <script src="/js/kavv/tiposmensajes.js"></script>
    
    <!-- Initialize the editor. -->
    <script>
        $(document).ready(function () {
            $('#limpiar').on('click', function (event) {
                event.preventDefault();
            });

            $('#limpiar').on('click', function (event) {
                event.preventDefault();
            });
        });

        function hidePassword() {
            //Kavv
            //only to follow the sequence but it is not necessary that it be established as invisible
            if($('#canReset').prop('checked'))
            {
                //ON
                $("#divPassword").css("visibility","visible");
                $("#divPassword").show()
                $('#changePassword').val(1);
            }
            else
            {
                //OFF
                $("#divPassword").css("visibility","hidden");
                $("#divPassword").hide()
                $('#changePassword').val(0);
            }
        }
        function generatePassword() {
            var length = 8,
                charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                retVal = "";
            for (var i = 0, n = charset.length; i < length; ++i) {
                retVal += charset.charAt(Math.floor(Math.random() * n));
            }
            return retVal;
        }
        
        @if(isset($usuario))
        //Update user
        function Update()
        {
            return $.ajax({
                url: '{{route('user.update',$usuario->id)}}',
                headers: {'X-CSRF-TOKEN': $("#token").val()},
                type: 'PUT',
                dataType: 'json',
                data: $("#data").serialize(),
                success: function(res){
                    if(res.action === 1)
                        //message([Message Array], {manual:bool,objeto:$(#),tipo:'danger,info,success, etc'})
                        message(res.message, {manual:true, tipo:'danger'});                  
                    else
                        location.href = "/dashboard/user";
                }
            }).fail( function( jqXHR, textStatus, errorThrown ) {
                message(jqXHR,{tipo:"danger"});
            });
        }
        @else 
        //Save User
        function Save()
        {
            return $.ajax({
                url: '{{route('user.store')}}',
                headers: {'X-CSRF-TOKEN': $("#token").val()},
                type: 'POST',
                dataType: 'json',
                data: $("#data").serialize(),
                success: function(res){
                    if(res.action === 1)
                        message(res.message, {manual:true, tipo:'danger'});                    
                    else
                        location.href = "/dashboard/user";
                }
            }).fail( function( jqXHR, textStatus, errorThrown ) {
                message(jqXHR,{tipo:"danger"});
            });
        }
        @endif
    </script>

    @parent
@stop

steps.web/resources/views/dashboard/user/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {{ Breadcrumbs::render('user.index') }}

    <div class="header text-center">
        <h3 class="title">Usuarios registrados en el sistema.</h3>
        <p class="category">lista de usuarios</p>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-content">
                    {{--@include('dashboard.partials.search')--}}
                    <div class="toolbar" style="display: inline-block; width: 100%;">
                        <div class="pull-left">
                            <div class="btn-group pull-left" style="margin-right: 10px">
                                <a href="{{action('UserController@create')}}">
                                    <button class="btn btn-sm btn-success">
                                        <i class="material-icons">save</i>&nbsp;&nbsp;Nuevo
                                    </button>
                                </a>
                            </div>
                        </div>
                        <div class="pull-right">
                            <div class="btn-group pull-right" style="margin-right: 10px">
                                <button class="btn btn-sm btn-facebook btn-raised"
                                        onclick="$('#filter').modal('show');">
                                    <i class="material-icons">filter_list</i>&nbsp;&nbsp;Filtrar
                                </button>
                                <button class="btn btn-sm reload btn-facebook btn-raised">
                                    <i class="material-icons">replay</i>&nbsp;&nbsp;Recargar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="material-datatables">
                        <table id="datatables" class="table table-striped table-no-bordered table-hover"
                               cellspacing="0"
                               width="100%" style="width:100%">
                            <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th>Nombre</th>
                                <th>Email</th>
                                <th>Roles</th>
                                <th>Fecha de creacion</th>
                                <th class="text-left">Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true" style="display: none;">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn btn-simple close" data-dismiss="modal"
                                        aria-hidden="true">
                                    <i class="material-icons">clear</i>
                                </button>
                                <h4 class="modal-title"></h4>
                            </div>
                            <div class="modal-body">
                                <p class="description-modal"></p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-simple" data-dismiss="modal">Cancelar</button>
                                <button type="button" class="btn btn-danger btn-simple delete" data-dismiss="modal">
                                    Sí
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="filter" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true" style="display: none;">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn btn-simple close" data-dismiss="modal"
                                        aria-hidden="true">
                                    <i class="material-icons">clear</i>
                                </button>
                                <h4 class="modal-title"></h4>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label>ID</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-pencil"></i>
                                            </div>
                                            <input type="text" class="form-control id" placeholder="ID" name="id"
                                                   value="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-simple" data-dismiss="modal">Cancelar</button>
                                <button type="button" class="btn btn-danger btn-simple filtrar" data-dismiss="modal">
                                    Filtrar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('javascript')

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatables').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{route('user.indexAjax')}}',
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'roles', name: 'roles', orderable:false, searchable:false},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
                columnDefs: [
                    {className: "td-actions text-right", "targets": [5]}
                ],
                "lengthMenu": [
                    [10, 25, 50],
                    [10, 25, 50]
                ],
                responsive: true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search records",
                    lengthMenu: "Ver _MENU_ por página",
                    zeroRecords: "No se encontraron coincidencias - :c",
                    info: "Página _PAGE_ de _PAGES_",
                    infoEmpty: "No hay datos",
                    paginate: {
                        first: "Primero",
                        last: "Último",
                        next: "Siguiente",
                        previous: "Anterior"
                    },
                    sProcessing: "<div id=\"contenedor\"><div class=\"loader\" id=\"loader\">Loading...</div></div>"
                }

            });
            var table = $('#datatables').DataTable();

            var theValue;
            $(document).on('click', '.remove', function () {
                $('.description-modal').text("Esta seguro que desea eliminar este registro");
                $('#myModal').modal('show');
                theValue = $(this).data('info');
                console.log(theValue);
            });
            $(document).on('click', '.delete', function (e) {
                $.ajax(
                    {
                        type: "POST",
                        url: '{{route('user.remove')}}',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        data: {
                            user: theValue
                        },
                        success: function () {
                            location.reload();
                        }
                    }
                );
            });
            $(document).on('click', '.reload', function (e) {
                location.reload();
            });
        });
    </script>
    @parent
@stop